[package]
name = "nucleus-abigen"
version = "0.1.0"
edition = "2021"

[dependencies]

clap = { version = "4.4.8", features = ["derive"] }
serde_json = "1.0.107"
glob = "0.3.1"                                      # For file pattern matching
